// Developer Express Code Central Example:
// How to: Manage documents via WindowedDocumentUIService and TabbedDocumentUIService
// 
// The WindowedDocumentUIService provides methods to create and show documents as
// windows.
// The TabbedDocumentUIService provides methods to create and show
// documents as tabs.
// The CurrentWindowService provides methods to close the
// current window.
// 
// The following example demonstrates how to use the above
// services in a View Model.
// 
// If you wish to perform some actions when the
// document is about to close or wish to prevent a document from being closed,
// implement the IDocumentViewModel interface for the view model that represents a
// document. The IDocumentViewModel.Close method will be called before the document
// closure.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4861

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentServiceTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
